SQL> INSERT INTO PROFESORES (APELLIDOS,ESPECIALIDAD,COD_CENTRO,DNI)
  2  VALUES('G¢nzalez Sevilla, Miguel A.,'HISTORIA',22,23444800);
ERROR:
ORA-01756: quoted string not properly terminated 


SQL> INSERT INTO PROFESORES (APELLIDOS,ESPECIALIDAD,COD_CENTRO,DNI)
  2  VALUES('G¢nzalez Sevilla, Miguel A.','HISTORIA',22,23444800);

1 row created.

SQL> INSERT INTO PROFESORES (APELLIDOS,ESPECIALIDAD,COD_CENTRO,DNI)
  2  VALUES('G¢nzalez Sevilla, Miguel A.','HISTORIADELAMUSICACONTEMPORANEA',22,23444800);
VALUES('G¢nzalez Sevilla, Miguel A.','HISTORIADELAMUSICACONTEMPORANEA',22,23444800)
                                      *
ERROR at line 2:
ORA-12899: value too large for column "DATOS"."PROFESORES"."ESPECIALIDAD" 
(actual: 31, maximum: 16) 

NO PODEMOS INSERTAR EL PROFESOR YA QUE EL TAMAÑO DE LA COLUMNA "ESPECIALIDAD" ESTÁ DEFINIDO HASTA 16 CARACTERES, COMO LO HEMOS SUPERADO POR ESO SALTA EL ERROR.

SQL> spool off
